# Generated by Django 2.1.5 on 2019-01-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_img/20190116_185717.jpg', upload_to='post_img/'),
        ),
    ]
