# Generated by Django 2.1.5 on 2019-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20190122_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_img/20190116_185717.jpg', upload_to='post_img/'),
        ),
    ]
